check:
    global:
        statements: 65
        lines: 65
        branches: 65
        functions: 65
reporting:
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
