check:
    global:
        statements: 80
        lines: 80
        branches: 80
        functions: 80
reporting:
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
